[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:frankenphp]
command=/usr/local/bin/frankenphp run --config /etc/caddy/Caddyfile
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/frankenphp.err.log
stdout_logfile=/var/log/supervisor/frankenphp.out.log
