<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Glodaxia Branding & Identity
    |--------------------------------------------------------------------------
    |
    | Global settings for the platform branding.
    |
    */

    'site_name' => 'Glodaxia',
    'tagline'   => 'Tech & News Magazine',
    'footer_text' => 'Glodaxia Digital Media',

    /*
    |--------------------------------------------------------------------------
    | Editorial & AI Settings
    |--------------------------------------------------------------------------
    |
    | Rules for content generation, word counts, and AI persona.
    |
    */

    'editorial' => [
        // Persona for the AI when redact articles
        'persona' => 'world-class Senior Technology Journalist and elite SEO copywriter (15+ years experience) working for Glodaxia, a premium tech publication.',
        
        // Strict focus for the AI
        'focus_rules' => 'STRICTLY ADHERE TO THE FACTS PROVIDED. NEVER invent names, dates, statistics, or events not present in the SOURCE FACTS.',

        // Word count targets per content type
        'word_targets' => [
            'news'   => '600-1000 words EN | 600-1000 palabras ES',
            'blog'   => '800-1200 words EN | 800-1200 palabras ES',
            'guide'  => '1000-1500 words EN | 1000-1500 palabras ES',
            'review' => '800-1200 words EN | 800-1200 palabras ES',
            'pillar' => '1500-2500 words EN | 1500-2500 palabras ES',
        ],

        // Default author creation if none exists
        'default_author' => [
            'name' => 'Redacción Glodaxia',
            'bio'  => [
                'en' => 'Expert editorial team focused on technology, innovation, and digital trends from Glodaxia.',
                'es' => 'Equipo editorial experto en tecnología, innovación y tendencias digitales de Glodaxia.',
            ],
            'voice_style' => 'Analytical',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Transparency & Features
    |--------------------------------------------------------------------------
    |
    | Feature flags for the frontend components.
    |
    */

    'features' => [
        'show_ai_disclaimers' => false, // Set to true to show "Generated by AI" labels
        'show_source_links'   => true,  // Set to true to show "Read original source" links
    ],
];
